language: c

env:
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=HEAD

before_install:
 - curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.3/install-racket.sh | sh

script:
 - export PATH=/usr/racket/bin:$PATH
 - raco pkg install base math-lib plot-gui-lib plot-lib srfi-lite-lib typed-racket-lib
 - raco pkg install -n benchmark --link ../racket-benchmark
 - cd benchmark/examples
 - make -k -j 4 all
